rootProject.name = "MeditationComposeApp"
include(":app")

include(":core:design_system")
include(":core:authentication_source")
include(":core:database")
include(":core:common")
include(":core:network")
include(":core:punk_source")
include(":core:model")
include(":core:data_store")
include(":core:updates_history")
include(":core:testing")

include(":feature:shuffle_puzzle")
include(":feature:authentication")
include(":feature:beer_sorts")
include(":feature:splash_screen")
include(":feature:main")
include(":feature:update_history")
include(":feature:internet_connection")
include(":feature:music_player")

include(":sample:music_player")
include(":sample:design_system")
